import {
  KPIMetric,
  AIHealthScore,
  LiveIncidentAlert,
  DigitalTwinNodeData,
  LiveTransportVehicle,
  GeoRiskZone,
  SimulationResultMetrics,
  CommodityPriceIndex,
  RiskMatrixItem,
  ReportSummaryItem,
  UserProfile,
  DemandForecastPoint,
  InventoryForecastPoint,
  Supplier,
  PortNode,
  Shipment,
  RiskItem,
  DigitalTwinNode,
  DigitalTwinEdge,
} from '../types';

export const mockAIHealth: AIHealthScore = {
  score: 96.8,
  status: 'optimal',
  resilienceRating: 'AAA (Enterprise Resilient)',
  lastUpdated: 'Just now (Live Telemetry)',
  activeDisruptionsCount: 3,
  predictedRiskEventsCount: 5,
  mitigationReadinessPct: 94.2,
  latencyMs: 14,
};

export const mockKPIMetrics: KPIMetric[] = [
  {
    id: 'kpi-suppliers',
    title: 'Total Active Suppliers',
    value: 248,
    suffix: ' Vendors',
    changePct: 3.4,
    isPositive: true,
    sparkline: [230, 235, 238, 240, 244, 246, 248],
    status: 'optimal',
    description: 'Tier-1 & Tier-2 global integrated suppliers',
    iconName: 'Building2',
  },
  {
    id: 'kpi-factories',
    title: 'Smart Factories / Hubs',
    value: 18,
    suffix: ' Plants',
    changePct: 0,
    isPositive: true,
    sparkline: [18, 18, 18, 18, 18, 18, 18],
    status: 'optimal',
    description: '100% operational throughput across 4 continents',
    iconName: 'Factory',
  },
  {
    id: 'kpi-warehouses',
    title: 'Global Warehouses',
    value: 42,
    suffix: ' Facilities',
    changePct: 5.0,
    isPositive: true,
    sparkline: [38, 39, 40, 40, 41, 41, 42],
    status: 'optimal',
    description: 'Average capacity utilization: 76.4%',
    iconName: 'Warehouse',
  },
  {
    id: 'kpi-inventory',
    title: 'Total Inventory Value',
    value: 142.8,
    prefix: '$',
    suffix: 'M',
    changePct: -1.8,
    isPositive: true,
    sparkline: [148, 146, 145, 144, 143, 142.5, 142.8],
    status: 'optimal',
    description: 'Optimized safety stock with AI buffer reduction',
    iconName: 'PackageCheck',
  },
  {
    id: 'kpi-revenue-risk',
    title: 'Revenue at Risk',
    value: 4.2,
    prefix: '$',
    suffix: 'M',
    changePct: -18.5,
    isPositive: true,
    sparkline: [6.8, 6.2, 5.5, 5.1, 4.8, 4.4, 4.2],
    status: 'warning',
    description: 'Threatened by Typhoon Gaemi & Taiwan port backlog',
    iconName: 'AlertTriangle',
  },
  {
    id: 'kpi-shipments',
    title: 'Shipments in Transit',
    value: 1280,
    suffix: ' Active',
    changePct: 8.2,
    isPositive: true,
    sparkline: [1120, 1150, 1190, 1210, 1240, 1265, 1280],
    status: 'optimal',
    description: '94.2% on-time delivery confidence',
    iconName: 'Truck',
  },
  {
    id: 'kpi-risk-score',
    title: 'Aggregate Risk Index',
    value: 34,
    suffix: '/100',
    changePct: -6.2,
    isPositive: true,
    sparkline: [45, 42, 40, 38, 36, 35, 34],
    status: 'optimal',
    description: 'Calculated from 14,000 real-time external telemetry feeds',
    iconName: 'ShieldCheck',
  },
  {
    id: 'kpi-orders',
    title: "Today's Processed Orders",
    value: 14290,
    suffix: ' SKUs',
    changePct: 12.4,
    isPositive: true,
    sparkline: [12100, 12400, 13000, 13200, 13800, 14100, 14290],
    status: 'optimal',
    description: 'Real-time ERP synchronization active',
    iconName: 'TrendingUp',
  },
];

export const mockIncidentAlerts: LiveIncidentAlert[] = [
  {
    id: 'inc-001',
    timestamp: '2 mins ago',
    title: 'Category 4 Typhoon Gaemi — East China Sea Port Alert',
    severity: 'critical',
    category: 'weather',
    source: 'NOAA Satellite Telemetry & Port Authority',
    impactSummary: 'Ningbo & Shanghai port operations throttled by 45%. 12 container vessels queued. Estimated delay: 3.5 days.',
    confidencePct: 96,
    isRead: false,
    actionRequired: true,
    recommendedActionTitle: 'Reroute 4 express vessels via Busan / Xiamen alternative corridors',
  },
  {
    id: 'inc-002',
    timestamp: '14 mins ago',
    title: 'Tier-2 Microcontroller Wafer Yield Anomaly at Hsinchu Fab',
    severity: 'high',
    category: 'supplier',
    source: 'SynChain AI Supplier IoT Health Monitor',
    impactSummary: 'Automotive ECU component supply reduced by 22,000 units over next 14 days.',
    confidencePct: 91,
    isRead: false,
    actionRequired: true,
    recommendedActionTitle: 'Trigger dual-source allocation from SK Hynix backup quota in Icheon',
  },
  {
    id: 'inc-003',
    timestamp: '1 hour ago',
    title: 'Hamburg Port Cargo Handler 24h Warning Strike',
    severity: 'medium',
    category: 'logistics',
    source: 'European Logistics Feed & Union Telemetry',
    impactSummary: 'Rail freight connections into Central Europe delayed by 18-24 hours.',
    confidencePct: 88,
    isRead: true,
    actionRequired: false,
    recommendedActionTitle: 'Divert intermodal trucks to Rotterdam Gateway C-Dock',
  },
  {
    id: 'inc-004',
    timestamp: '3 hours ago',
    title: 'Lithium Battery Precursor Freight Rate Spike (+18%)',
    severity: 'low',
    category: 'inventory',
    source: 'Drewry Global Freight Index',
    impactSummary: 'Trans-Pacific spot freight container costs adjusted upward.',
    confidencePct: 94,
    isRead: true,
    actionRequired: false,
  },
];

// Digital Twin Graph Data (React Flow)
export const mockDigitalTwinNodes: Array<{ id: string; position: { x: number; y: number }; data: DigitalTwinNodeData }> = [
  {
    id: 'node-t2-tsmc',
    position: { x: 50, y: 80 },
    data: {
      label: 'TSMC Fab 18 (Hsinchu)',
      nodeType: 'tier2_supplier',
      tier: 2,
      location: 'Hsinchu, Taiwan',
      country: 'TW',
      coordinates: [24.77, 120.99],
      healthStatus: 'warning',
      riskScore: 68,
      failureProb: 34.5,
      inventoryPct: 62,
      capacityUtilization: 94,
      throughputUnitsPerDay: 45000,
      leadTimeDays: 28,
      currentOrdersCount: 142,
      annualSpendUsd: 48500000,
      upstreamIds: [],
      downstreamIds: ['node-t1-foxconn', 'node-t1-bosch'],
      primaryProduct: '3nm / 5nm High Performance AI Accelerators & ECUs',
      recommendedMitigation: 'Activate SK Hynix secondary production buffer allocation.',
    },
  },
  {
    id: 'node-t2-skhynix',
    position: { x: 50, y: 260 },
    data: {
      label: 'SK Hynix Memory Complex',
      nodeType: 'tier2_supplier',
      tier: 2,
      location: 'Icheon, South Korea',
      country: 'KR',
      coordinates: [37.28, 127.44],
      healthStatus: 'optimal',
      riskScore: 18,
      failureProb: 4.2,
      inventoryPct: 91,
      capacityUtilization: 82,
      throughputUnitsPerDay: 80000,
      leadTimeDays: 14,
      currentOrdersCount: 210,
      annualSpendUsd: 36000000,
      upstreamIds: [],
      downstreamIds: ['node-t1-foxconn', 'node-t1-denso'],
      primaryProduct: 'HBM3e & LPDDR5X Ultra-Dense Memory Modules',
    },
  },
  {
    id: 'node-t2-basf',
    position: { x: 50, y: 440 },
    data: {
      label: 'BASF Chemical Synthesis Verbund',
      nodeType: 'tier2_supplier',
      tier: 2,
      location: 'Ludwigshafen, Germany',
      country: 'DE',
      coordinates: [49.48, 8.44],
      healthStatus: 'optimal',
      riskScore: 24,
      failureProb: 7.1,
      inventoryPct: 84,
      capacityUtilization: 88,
      throughputUnitsPerDay: 12000,
      leadTimeDays: 18,
      currentOrdersCount: 95,
      annualSpendUsd: 19800000,
      upstreamIds: [],
      downstreamIds: ['node-t1-bosch'],
      primaryProduct: 'Engineered Thermal Polymers & Battery Electrolytes',
    },
  },
  {
    id: 'node-t1-foxconn',
    position: { x: 380, y: 120 },
    data: {
      label: 'Foxconn Precision Industrial Park',
      nodeType: 'tier1_supplier',
      tier: 1,
      location: 'Shenzhen, China',
      country: 'CN',
      coordinates: [22.54, 114.05],
      healthStatus: 'warning',
      riskScore: 54,
      failureProb: 21.0,
      inventoryPct: 70,
      capacityUtilization: 91,
      throughputUnitsPerDay: 150000,
      leadTimeDays: 12,
      currentOrdersCount: 420,
      annualSpendUsd: 82000000,
      upstreamIds: ['node-t2-tsmc', 'node-t2-skhynix'],
      downstreamIds: ['node-factory-austin', 'node-factory-shanghai'],
      primaryProduct: 'Integrated Compute Motherboards & Power Distribution Units',
      recommendedMitigation: 'Schedule air-freight expedited batch to avoid port queues.',
    },
  },
  {
    id: 'node-t1-bosch',
    position: { x: 380, y: 320 },
    data: {
      label: 'Bosch Mobility Solutions Hub',
      nodeType: 'tier1_supplier',
      tier: 1,
      location: 'Stuttgart, Germany',
      country: 'DE',
      coordinates: [48.77, 9.18],
      healthStatus: 'optimal',
      riskScore: 22,
      failureProb: 5.6,
      inventoryPct: 88,
      capacityUtilization: 79,
      throughputUnitsPerDay: 65000,
      leadTimeDays: 9,
      currentOrdersCount: 185,
      annualSpendUsd: 54000000,
      upstreamIds: ['node-t2-tsmc', 'node-t2-basf'],
      downstreamIds: ['node-factory-munich', 'node-factory-austin'],
      primaryProduct: 'Drive Inverters & Smart Sensor Actuator Subsystems',
    },
  },
  {
    id: 'node-t1-denso',
    position: { x: 380, y: 490 },
    data: {
      label: 'Denso Advanced Tech Plant',
      nodeType: 'tier1_supplier',
      tier: 1,
      location: 'Kariya, Nagoya, Japan',
      country: 'JP',
      coordinates: [34.99, 137.0],
      healthStatus: 'optimal',
      riskScore: 16,
      failureProb: 3.1,
      inventoryPct: 93,
      capacityUtilization: 84,
      throughputUnitsPerDay: 48000,
      leadTimeDays: 8,
      currentOrdersCount: 130,
      annualSpendUsd: 38500000,
      upstreamIds: ['node-t2-skhynix'],
      downstreamIds: ['node-factory-shanghai', 'node-factory-austin'],
      primaryProduct: 'Thermal Management Systems & Radar Array Modules',
    },
  },
  {
    id: 'node-factory-austin',
    position: { x: 720, y: 150 },
    data: {
      label: 'Giga Plant Austin (Factory 01)',
      nodeType: 'factory',
      location: 'Austin, Texas, USA',
      country: 'US',
      coordinates: [30.22, -97.62],
      healthStatus: 'optimal',
      riskScore: 26,
      failureProb: 6.8,
      inventoryPct: 82,
      capacityUtilization: 96,
      throughputUnitsPerDay: 2800,
      leadTimeDays: 4,
      currentOrdersCount: 650,
      annualSpendUsd: 140000000,
      upstreamIds: ['node-t1-foxconn', 'node-t1-bosch', 'node-t1-denso'],
      downstreamIds: ['node-wh-memphis'],
      primaryProduct: 'Flagship Autonomous AI Systems & Next-Gen Hardware',
    },
  },
  {
    id: 'node-factory-munich',
    position: { x: 720, y: 340 },
    data: {
      label: 'Munich Mega Assembly (Factory 02)',
      nodeType: 'factory',
      location: 'Munich, Bavaria, Germany',
      country: 'DE',
      coordinates: [48.13, 11.58],
      healthStatus: 'optimal',
      riskScore: 20,
      failureProb: 4.8,
      inventoryPct: 86,
      capacityUtilization: 89,
      throughputUnitsPerDay: 1950,
      leadTimeDays: 5,
      currentOrdersCount: 420,
      annualSpendUsd: 95000000,
      upstreamIds: ['node-t1-bosch'],
      downstreamIds: ['node-wh-rotterdam'],
      primaryProduct: 'Precision Industrial Robotics & Medical AI Scanners',
    },
  },
  {
    id: 'node-factory-shanghai',
    position: { x: 720, y: 500 },
    data: {
      label: 'Shanghai Smart Gigafactory (Factory 03)',
      nodeType: 'factory',
      location: 'Shanghai Lingang, China',
      country: 'CN',
      coordinates: [30.91, 121.92],
      healthStatus: 'warning',
      riskScore: 62,
      failureProb: 28.0,
      inventoryPct: 66,
      capacityUtilization: 85,
      throughputUnitsPerDay: 3200,
      leadTimeDays: 6,
      currentOrdersCount: 580,
      annualSpendUsd: 115000000,
      upstreamIds: ['node-t1-foxconn', 'node-t1-denso'],
      downstreamIds: ['node-wh-singapore'],
      primaryProduct: 'High-Volume Enterprise Systems & Energy Storage Packs',
    },
  },
  {
    id: 'node-wh-memphis',
    position: { x: 1060, y: 100 },
    data: {
      label: 'Memphis Global Air & Freight SuperHub',
      nodeType: 'warehouse',
      location: 'Memphis, Tennessee, USA',
      country: 'US',
      coordinates: [35.04, -89.97],
      healthStatus: 'optimal',
      riskScore: 14,
      failureProb: 2.1,
      inventoryPct: 92,
      capacityUtilization: 78,
      throughputUnitsPerDay: 34000,
      leadTimeDays: 2,
      currentOrdersCount: 1200,
      annualSpendUsd: 28000000,
      upstreamIds: ['node-factory-austin'],
      downstreamIds: ['node-cust-enterprise-us'],
      primaryProduct: 'Strategic Central North American Inventory',
    },
  },
  {
    id: 'node-wh-rotterdam',
    position: { x: 1060, y: 300 },
    data: {
      label: 'Rotterdam EuroGateway MegaHub',
      nodeType: 'warehouse',
      location: 'Rotterdam, Netherlands',
      country: 'NL',
      coordinates: [51.92, 4.47],
      healthStatus: 'optimal',
      riskScore: 19,
      failureProb: 4.5,
      inventoryPct: 89,
      capacityUtilization: 81,
      throughputUnitsPerDay: 28000,
      leadTimeDays: 3,
      currentOrdersCount: 950,
      annualSpendUsd: 22000000,
      upstreamIds: ['node-factory-munich'],
      downstreamIds: ['node-cust-enterprise-eu'],
      primaryProduct: 'European Central Logistics & Intermodal Cross-Dock',
    },
  },
  {
    id: 'node-wh-singapore',
    position: { x: 1060, y: 490 },
    data: {
      label: 'Singapore Tuas Mega Hub',
      nodeType: 'warehouse',
      location: 'Tuas Port, Singapore',
      country: 'SG',
      coordinates: [1.32, 103.65],
      healthStatus: 'optimal',
      riskScore: 21,
      failureProb: 5.2,
      inventoryPct: 85,
      capacityUtilization: 84,
      throughputUnitsPerDay: 31000,
      leadTimeDays: 3,
      currentOrdersCount: 890,
      annualSpendUsd: 24500000,
      upstreamIds: ['node-factory-shanghai'],
      downstreamIds: ['node-cust-enterprise-apac'],
      primaryProduct: 'APAC Maritime Distribution & Fast-Turnover SKUs',
    },
  },
  {
    id: 'node-cust-enterprise-us',
    position: { x: 1390, y: 120 },
    data: {
      label: 'North America Enterprise Tier-0 Clients',
      nodeType: 'customer',
      location: 'New York / Chicago / Silicon Valley',
      country: 'US',
      coordinates: [40.71, -74.0],
      healthStatus: 'optimal',
      riskScore: 10,
      failureProb: 1.0,
      inventoryPct: 98,
      capacityUtilization: 95,
      throughputUnitsPerDay: 18000,
      leadTimeDays: 1,
      currentOrdersCount: 3400,
      annualSpendUsd: 320000000,
      upstreamIds: ['node-wh-memphis'],
      downstreamIds: [],
      primaryProduct: 'Delivered Enterprise Systems & Service Contracts',
    },
  },
];

export const mockDigitalTwinEdges = [
  { id: 'e-t2tsmc-t1fox', source: 'node-t2-tsmc', target: 'node-t1-foxconn', animated: true, style: { stroke: '#3B82F6', strokeWidth: 2.5 } },
  { id: 'e-t2tsmc-t1bos', source: 'node-t2-tsmc', target: 'node-t1-bosch', animated: true, style: { stroke: '#F59E0B', strokeWidth: 2 } },
  { id: 'e-t2skh-t1fox', source: 'node-t2-skhynix', target: 'node-t1-foxconn', animated: true, style: { stroke: '#22C55E', strokeWidth: 2 } },
  { id: 'e-t2skh-t1den', source: 'node-t2-skhynix', target: 'node-t1-denso', animated: true, style: { stroke: '#22C55E', strokeWidth: 2 } },
  { id: 'e-t2basf-t1bos', source: 'node-t2-basf', target: 'node-t1-bosch', animated: true, style: { stroke: '#22C55E', strokeWidth: 2 } },
  { id: 'e-t1fox-facAus', source: 'node-t1-foxconn', target: 'node-factory-austin', animated: true, style: { stroke: '#3B82F6', strokeWidth: 3 } },
  { id: 'e-t1fox-facSha', source: 'node-t1-foxconn', target: 'node-factory-shanghai', animated: true, style: { stroke: '#F59E0B', strokeWidth: 2.5 } },
  { id: 'e-t1bos-facMun', source: 'node-t1-bosch', target: 'node-factory-munich', animated: true, style: { stroke: '#22C55E', strokeWidth: 2.5 } },
  { id: 'e-t1bos-facAus', source: 'node-t1-bosch', target: 'node-factory-austin', animated: true, style: { stroke: '#3B82F6', strokeWidth: 2 } },
  { id: 'e-t1den-facSha', source: 'node-t1-denso', target: 'node-factory-shanghai', animated: true, style: { stroke: '#22C55E', strokeWidth: 2 } },
  { id: 'e-t1den-facAus', source: 'node-t1-denso', target: 'node-factory-austin', animated: true, style: { stroke: '#3B82F6', strokeWidth: 2 } },
  { id: 'e-facAus-whMem', source: 'node-factory-austin', target: 'node-wh-memphis', animated: true, style: { stroke: '#22C55E', strokeWidth: 3 } },
  { id: 'e-facMun-whRot', source: 'node-factory-munich', target: 'node-wh-rotterdam', animated: true, style: { stroke: '#22C55E', strokeWidth: 3 } },
  { id: 'e-facSha-whSin', source: 'node-factory-shanghai', target: 'node-wh-singapore', animated: true, style: { stroke: '#F59E0B', strokeWidth: 2.5 } },
  { id: 'e-whMem-custUs', source: 'node-wh-memphis', target: 'node-cust-enterprise-us', animated: true, style: { stroke: '#22C55E', strokeWidth: 3.5 } },
];

export const mockNodesFlat: DigitalTwinNode[] = [
  { id: 'node-t2-tsmc', label: 'TSMC Fab 18 (Hsinchu)', type: 'tier2_supplier', tier: 2, country: 'TW', status: 'warning', riskScore: 68, failureProb: 34.5, capacityUtilization: 94, currentOrdersCount: 142, leadTimeDays: 28, primaryProduct: '3nm / 5nm AI Accelerators', upstreamIds: [], downstreamIds: ['node-t1-foxconn', 'node-t1-bosch'] },
  { id: 'node-t2-skhynix', label: 'SK Hynix Memory Complex', type: 'tier2_supplier', tier: 2, country: 'KR', status: 'optimal', riskScore: 18, failureProb: 4.2, capacityUtilization: 82, currentOrdersCount: 210, leadTimeDays: 14, primaryProduct: 'HBM3e Memory', upstreamIds: [], downstreamIds: ['node-t1-foxconn', 'node-t1-denso'] },
  { id: 'node-t2-basf', label: 'BASF Chemical Synthesis', type: 'tier2_supplier', tier: 2, country: 'DE', status: 'optimal', riskScore: 24, failureProb: 7.1, capacityUtilization: 88, currentOrdersCount: 95, leadTimeDays: 18, primaryProduct: 'Thermal Polymers', upstreamIds: [], downstreamIds: ['node-t1-bosch'] },
  { id: 'node-t1-foxconn', label: 'Foxconn Precision Park', type: 'tier1_supplier', tier: 1, country: 'CN', status: 'warning', riskScore: 54, failureProb: 21.0, capacityUtilization: 91, currentOrdersCount: 420, leadTimeDays: 12, primaryProduct: 'Compute Motherboards', upstreamIds: ['node-t2-tsmc', 'node-t2-skhynix'], downstreamIds: ['node-factory-austin', 'node-factory-shanghai'] },
  { id: 'node-t1-bosch', label: 'Bosch Mobility Solutions', type: 'tier1_supplier', tier: 1, country: 'DE', status: 'optimal', riskScore: 22, failureProb: 5.6, capacityUtilization: 79, currentOrdersCount: 185, leadTimeDays: 9, primaryProduct: 'Drive Inverters', upstreamIds: ['node-t2-tsmc', 'node-t2-basf'], downstreamIds: ['node-factory-munich', 'node-factory-austin'] },
  { id: 'node-t1-denso', label: 'Denso Advanced Tech', type: 'tier1_supplier', tier: 1, country: 'JP', status: 'optimal', riskScore: 16, failureProb: 3.1, capacityUtilization: 84, currentOrdersCount: 130, leadTimeDays: 8, primaryProduct: 'Thermal Systems', upstreamIds: ['node-t2-skhynix'], downstreamIds: ['node-factory-shanghai', 'node-factory-austin'] },
  { id: 'node-factory-austin', label: 'Giga Plant Austin', type: 'factory', country: 'US', status: 'optimal', riskScore: 26, failureProb: 6.8, capacityUtilization: 96, currentOrdersCount: 650, leadTimeDays: 4, primaryProduct: 'Autonomous AI Hardware', upstreamIds: ['node-t1-foxconn', 'node-t1-bosch'], downstreamIds: ['node-wh-memphis'] },
  { id: 'node-wh-memphis', label: 'Memphis Global SuperHub', type: 'warehouse', country: 'US', status: 'optimal', riskScore: 14, failureProb: 2.1, capacityUtilization: 78, currentOrdersCount: 1200, leadTimeDays: 2, primaryProduct: 'Strategic Central Inventory', upstreamIds: ['node-factory-austin'], downstreamIds: ['node-cust-enterprise-us'] },
];

export const mockEdgesFlat: DigitalTwinEdge[] = [
  { id: 'e1', source: 'node-t2-tsmc', target: 'node-t1-foxconn', flowRateUnits: 45000, activeCargoValueUsd: 14800000, transitHours: 36, status: 'warning', isBottleneck: true, transportMode: 'ocean' },
  { id: 'e2', source: 'node-t2-skhynix', target: 'node-t1-foxconn', flowRateUnits: 80000, activeCargoValueUsd: 22500000, transitHours: 18, status: 'optimal', transportMode: 'air' },
  { id: 'e3', source: 'node-t1-foxconn', target: 'node-factory-austin', flowRateUnits: 150000, activeCargoValueUsd: 48000000, transitHours: 72, status: 'warning', isBottleneck: true, transportMode: 'ocean' },
  { id: 'e4', source: 'node-factory-austin', target: 'node-wh-memphis', flowRateUnits: 2800, activeCargoValueUsd: 12000000, transitHours: 12, status: 'optimal', transportMode: 'ground' },
];

export const mockSuppliers: Supplier[] = [
  { id: 'sup-01', name: 'TSMC Semiconductor Foundry', tier: 'Tier-2', category: 'Semiconductor Fabrication', country: 'Taiwan', reliabilityScore: 98.4, spendAnnualUsd: 48500000, healthStatus: 'warning', singleSourceRisk: true },
  { id: 'sup-02', name: 'Foxconn Technology Group', tier: 'Tier-1', category: 'Precision Assembly & Electronics', country: 'China', reliabilityScore: 94.2, spendAnnualUsd: 82000000, healthStatus: 'warning', singleSourceRisk: false },
  { id: 'sup-03', name: 'SK Hynix Memory Corp', tier: 'Tier-2', category: 'HBM3e High Bandwidth Memory', country: 'South Korea', reliabilityScore: 99.1, spendAnnualUsd: 36000000, healthStatus: 'optimal', singleSourceRisk: false },
  { id: 'sup-04', name: 'Robert Bosch GmbH', tier: 'Tier-1', category: 'Inverters & Power Electronics', country: 'Germany', reliabilityScore: 97.6, spendAnnualUsd: 54000000, healthStatus: 'optimal', singleSourceRisk: false },
  { id: 'sup-05', name: 'BASF Advanced Materials', tier: 'Tier-2', category: 'Specialty Polymers & Chemistry', country: 'Germany', reliabilityScore: 96.8, spendAnnualUsd: 19800000, healthStatus: 'optimal', singleSourceRisk: false },
  { id: 'sup-06', name: 'Denso Corporation', tier: 'Tier-1', category: 'Thermal Actuators & Radar Sensors', country: 'Japan', reliabilityScore: 98.9, spendAnnualUsd: 38500000, healthStatus: 'optimal', singleSourceRisk: false },
];

export const mockPorts: PortNode[] = [
  { id: 'port-shanghai', name: 'Port of Shanghai (Yangshan)', country: 'CN', coordinates: [31.23, 121.47], status: 'warning', congestionIndex: 78, waitTimeDays: 3.5 },
  { id: 'port-ningbo', name: 'Ningbo-Zhoushan Port', country: 'CN', coordinates: [29.86, 121.54], status: 'critical', congestionIndex: 91, waitTimeDays: 4.8 },
  { id: 'port-rotterdam', name: 'Port of Rotterdam EuroGate', country: 'NL', coordinates: [51.92, 4.47], status: 'optimal', congestionIndex: 28, waitTimeDays: 0.8 },
  { id: 'port-singapore', name: 'Port of Singapore (PSA Tuas)', country: 'SG', coordinates: [1.32, 103.65], status: 'optimal', congestionIndex: 32, waitTimeDays: 1.1 },
  { id: 'port-la', name: 'Port of Los Angeles / Long Beach', country: 'US', coordinates: [33.74, -118.26], status: 'optimal', congestionIndex: 44, waitTimeDays: 1.4 },
];

export const mockShipments: Shipment[] = [
  { id: 'SHP-9842', carrier: 'CMA CGM Global', mode: 'ocean', origin: 'Port of Shanghai', destination: 'Port of Los Angeles', cargoDescription: '18,500 TEU High-Value Compute & Microchips', speedKnots: 21.4, eta: 'Aug 08, 14:00 UTC', status: 'optimal', vesselName: 'CMA CGM Palais Royal' },
  { id: 'SHP-7729', carrier: 'Lufthansa Cargo / SynChain', mode: 'air', origin: 'Taipei Taoyuan (TPE)', destination: 'Frankfurt Cargo City (FRA)', cargoDescription: '102 Tons Priority Automotive AI Sensors', speedKnots: 480, eta: 'Today, 21:30 UTC', status: 'optimal', vesselName: 'CARGO-7729 (Boeing 777F)' },
  { id: 'SHP-4109', carrier: 'Evergreen Marine', mode: 'ocean', origin: 'Ningbo-Zhoushan Port', destination: 'Rotterdam Maasvlakte', cargoDescription: '14,200 TEU Industrial Assembly Hardware', speedKnots: 12.8, eta: 'Aug 19, 06:00 UTC', status: 'delayed', vesselName: 'Ever Given Maritime VII', rerouteRecommendation: 'Divert to Busan Transshipment Terminal (+1.2 days recovery)' },
  { id: 'SHP-3310', carrier: 'Atlas Air Express', mode: 'air', origin: 'Seoul Incheon (ICN)', destination: "Chicago O'Hare (ORD)", cargoDescription: '94 Tons HBM3e Memory Components', speedKnots: 495, eta: 'Today, 23:10 UTC', status: 'optimal', vesselName: 'Atlas Air Polar-41' },
];

export const mockRisks: RiskItem[] = [
  { id: 'r1', title: 'Taiwan Strait Maritime Congestion (Typhoon Gaemi)', category: 'Weather', probability: 5, severityScore: 4, severity: 'critical', compositeScore: 20, affectedEntity: 'Port of Shanghai & Ningbo', financialImpactUsd: 18450000, mitigationAction: 'Reroute express air charters from Shenzhen directly to Austin.' },
  { id: 'r2', title: 'TSMC Wafer Fab 18 Contamination Alert', category: 'Supplier', probability: 4, severityScore: 5, severity: 'critical', compositeScore: 20, affectedEntity: 'TSMC Hsinchu Fab', financialImpactUsd: 24000000, mitigationAction: 'Trigger dual-source allocation from SK Hynix quota in Icheon.' },
  { id: 'r3', title: 'Red Sea Transit Surcharges & Rerouting', category: 'Geopolitical', probability: 4, severityScore: 3, severity: 'high', compositeScore: 12, affectedEntity: 'Rotterdam & Hamburg Maritime Corridor', financialImpactUsd: 4800000, mitigationAction: 'Lock 6-month fixed maritime charter contracts.' },
  { id: 'r4', title: 'Hamburg Port Cargo Handler Strike', category: 'Logistics', probability: 3, severityScore: 3, severity: 'medium', compositeScore: 9, affectedEntity: 'Hamburg Intermodal Rail Hub', financialImpactUsd: 1200000, mitigationAction: 'Divert intermodal fleet to Rotterdam Gateway C-Dock.' },
  { id: 'r5', title: 'Lithium Hydroxide Commodity Price Spike', category: 'Financial', probability: 3, severityScore: 2, severity: 'low', compositeScore: 6, affectedEntity: 'Giga Plant Austin Battery Packs', financialImpactUsd: 850000, mitigationAction: 'Hedge raw materials via CME forward contracts.' },
];

export const mockCommodityPrices: CommodityPriceIndex[] = [
  {
    materialName: 'Lithium Hydroxide (Battery Grade)',
    currentPriceUsd: 14200,
    forecastPriceUsd: 13900,
    changePct30d: -2.1,
    unit: 'Ton',
    historicalDates: ['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'],
    historicalPrices: [15400, 15100, 14800, 14500, 14200, 13900],
  },
  {
    materialName: 'Silicon Wafer Substrates (300mm)',
    currentPriceUsd: 125,
    forecastPriceUsd: 142,
    changePct30d: 13.6,
    unit: 'Wafer',
    historicalDates: ['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'],
    historicalPrices: [110, 115, 118, 122, 125, 142],
  },
  {
    materialName: 'Copper Cathode Grade A',
    currentPriceUsd: 9650,
    forecastPriceUsd: 9980,
    changePct30d: 3.4,
    unit: 'MT',
    historicalDates: ['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'],
    historicalPrices: [9200, 9350, 9480, 9550, 9650, 9980],
  },
  {
    materialName: 'Aviation Jet Fuel (Kerosene)',
    currentPriceUsd: 782,
    forecastPriceUsd: 815,
    changePct30d: 4.2,
    unit: 'MT',
    historicalDates: ['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'],
    historicalPrices: [740, 755, 762, 770, 782, 815],
  },
];

export const mockCommodityIndices = mockCommodityPrices;
export const mockRiskMatrixItems = mockRisks;

export const mockDefaultSimulationResult: SimulationResultMetrics = {
  scenarioId: 'sim-result-live-09',
  scenarioName: 'Typhoon Gaemi (East China Sea Port Closure)',
  createdAt: '2026-08-05 18:00:00 UTC',
  financialLossEstimateUsd: 18450000,
  lostProductionUnits: 14200,
  estimatedDelayDays: 8.4,
  riskScorePostSimulation: 78,
  productionLossUnits: 14200,
  productionLossPct: 18.4,
  estimatedRevenueLossUsd: 18450000,
  slaPenaltyCostUsd: 2800000,
  expeditedRecoveryCostUsd: 1450000,
  netFinancialExposureUsd: 22700000,
  daysToStockout: 7,
  averageShipmentDelayDays: 8.4,
  preRiskScore: 34,
  postRiskScore: 78,
  mitigatedRiskScore: 28,
  affectedProductLines: ['Autonomous AI Edge Server Pro', 'Giga Compute Cluster X', 'Drive Inverter Gen-4'],
  affectedCustomerOrdersCount: 148,
  dailyImpactTrend: [
    { day: 1, lossWithoutMitigation: 100000, lossWithMitigation: 80000 },
    { day: 3, lossWithoutMitigation: 650000, lossWithMitigation: 250000 },
    { day: 5, lossWithoutMitigation: 2200000, lossWithMitigation: 600000 },
    { day: 7, lossWithoutMitigation: 5800000, lossWithMitigation: 1200000 },
    { day: 10, lossWithoutMitigation: 11400000, lossWithMitigation: 2100000 },
    { day: 14, lossWithoutMitigation: 18450000, lossWithMitigation: 3200000 },
  ],
  cascadingTimeline: [
    { day: 1, affectedEntity: 'Port of Shanghai & Ningbo', description: 'Berths shut down due to 145 kn typhoon gusts; 45,000 TEU microelectronics stranded.', impactLevel: 'critical' },
    { day: 4, affectedEntity: 'Foxconn Precision Park', description: 'Motherboard sub-assembly buffer depleted by 80%; assembly line idle risk.', impactLevel: 'high' },
    { day: 8, affectedEntity: 'Giga Plant Austin', description: 'Drive inverter and ECU starvation triggers temporary shift stoppage.', impactLevel: 'critical' },
    { day: 14, affectedEntity: 'Global Enterprise Deliveries', description: 'Customer deliveries delayed by +12.4 days with $2.8M SLA penalty risk.', impactLevel: 'high' },
  ],
  mitigationStrategies: [
    {
      id: 'mit-1',
      title: 'Authorize SK Hynix Dual-Sourcing Allocation (65,000 Wafers)',
      description: 'Activate secondary supplier agreement to divert 35% of wafer fabrication volume to Icheon, bypassing Taiwan port congestion.',
      category: 'dual_sourcing',
      costEstimateUsd: 420000,
      savingsEstimateUsd: 2800000,
      timeSavedDays: 12,
      implementationTimeframe: '24-48 Hours',
      status: 'pending',
    },
    {
      id: 'mit-2',
      title: 'Charter Boeing 777F Air Cargo for Microcontroller Batch #892',
      description: 'Bypass maritime typhoon delay by dispatching high-density silicon microchips via direct Taipei -> Austin air freight.',
      category: 'expedited_freight',
      costEstimateUsd: 260000,
      savingsEstimateUsd: 1950000,
      timeSavedDays: 9,
      implementationTimeframe: '12 Hours',
      status: 'pending',
    },
    {
      id: 'mit-3',
      title: 'Release Memphis Tier-2 Strategic Safety Buffer (18,000 Units)',
      description: 'Drawdown reserved regional safety stock to maintain continuous assembly lines in Texas while maritime transit normalizes.',
      category: 'buffer_release',
      costEstimateUsd: 95000,
      savingsEstimateUsd: 1400000,
      timeSavedDays: 7,
      implementationTimeframe: 'Immediate',
      status: 'pending',
    },
  ],
};

export const mockDemandForecast: DemandForecastPoint[] = [
  { date: 'Jan 2026', actualDemandUnits: 42000, predictedDemandUnits: 41800, confidenceLower: 40000, confidenceUpper: 43500, historicalBaseline: 39000 },
  { date: 'Feb 2026', actualDemandUnits: 45200, predictedDemandUnits: 44900, confidenceLower: 43000, confidenceUpper: 46800, historicalBaseline: 41000 },
  { date: 'Mar 2026', actualDemandUnits: 48900, predictedDemandUnits: 48200, confidenceLower: 46200, confidenceUpper: 50100, historicalBaseline: 43500 },
  { date: 'Apr 2026', actualDemandUnits: 51200, predictedDemandUnits: 51600, confidenceLower: 49500, confidenceUpper: 53800, historicalBaseline: 46000 },
  { date: 'May 2026', actualDemandUnits: 54800, predictedDemandUnits: 55000, confidenceLower: 52800, confidenceUpper: 57200, historicalBaseline: 48200 },
  { date: 'Jun 2026', actualDemandUnits: 59100, predictedDemandUnits: 58800, confidenceLower: 56400, confidenceUpper: 61200, historicalBaseline: 51000 },
  { date: 'Jul 2026', actualDemandUnits: 62400, predictedDemandUnits: 62100, confidenceLower: 59500, confidenceUpper: 64800, historicalBaseline: 53500 },
  { date: 'Aug 2026', predictedDemandUnits: 66800, confidenceLower: 63800, confidenceUpper: 69800, historicalBaseline: 56000 },
  { date: 'Sep 2026', predictedDemandUnits: 71200, confidenceLower: 67500, confidenceUpper: 74900, historicalBaseline: 59000 },
  { date: 'Oct 2026', predictedDemandUnits: 75900, confidenceLower: 71200, confidenceUpper: 80600, historicalBaseline: 62000 },
  { date: 'Nov 2026', predictedDemandUnits: 82400, confidenceLower: 76800, confidenceUpper: 88000, historicalBaseline: 66000 },
  { date: 'Dec 2026', predictedDemandUnits: 89600, confidenceLower: 82500, confidenceUpper: 96800, historicalBaseline: 71000 },
];

export const mockInventoryForecast: InventoryForecastPoint[] = [
  { date: 'Week 1', projectedStock: 48000, safetyStockFloor: 22000, reorderTriggerPoint: 30000, stockoutRiskPct: 1.2 },
  { date: 'Week 2', projectedStock: 44200, safetyStockFloor: 22000, reorderTriggerPoint: 30000, stockoutRiskPct: 2.1 },
  { date: 'Week 3', projectedStock: 39500, safetyStockFloor: 22000, reorderTriggerPoint: 30000, stockoutRiskPct: 3.4 },
  { date: 'Week 4', projectedStock: 33800, safetyStockFloor: 22000, reorderTriggerPoint: 30000, stockoutRiskPct: 6.8 },
  { date: 'Week 5', projectedStock: 28400, safetyStockFloor: 22000, reorderTriggerPoint: 30000, stockoutRiskPct: 14.2 },
  { date: 'Week 6 (PO Arrival)', projectedStock: 52000, safetyStockFloor: 22000, reorderTriggerPoint: 30000, stockoutRiskPct: 1.0 },
  { date: 'Week 7', projectedStock: 47100, safetyStockFloor: 22000, reorderTriggerPoint: 30000, stockoutRiskPct: 1.5 },
  { date: 'Week 8', projectedStock: 41800, safetyStockFloor: 22000, reorderTriggerPoint: 30000, stockoutRiskPct: 2.8 },
];

export const mockReports: ReportSummaryItem[] = [
  {
    id: 'rep-001',
    title: 'Q3 Global Supply Chain Resilience & Disruption Audit',
    category: 'Executive Summary',
    generatedDate: '2026-08-04',
    generatedBy: 'SynChain AI Neural Core',
    fileFormat: 'PDF',
    fileSize: '4.8 MB',
    summaryMetrics: {
      totalValueAudited: '$1.42B Spend',
      identifiedSavings: '$32.4M',
      criticalAlertsResolved: 28,
    },
  },
  {
    id: 'rep-002',
    title: 'Typhoon Gaemi Disruption Simulation & Mitigation Playbook',
    category: 'Simulation Audit',
    generatedDate: '2026-08-05',
    generatedBy: 'Elena Vance (VP Supply Chain)',
    fileFormat: 'PDF',
    fileSize: '2.4 MB',
    summaryMetrics: {
      totalValueAudited: '$22.7M Risk Exposure',
      identifiedSavings: '$14.8M Loss Avoided',
      criticalAlertsResolved: 3,
    },
  },
];

export const mockUserProfiles: UserProfile[] = [
  {
    id: 'user-01',
    name: 'Elena Vance',
    email: 'elena.vance@synchain.ai',
    role: 'VP Supply Chain',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=256',
    department: 'Global Operations & Executive Strategy',
    accessTier: 'Enterprise Admin',
  },
  {
    id: 'user-02',
    name: 'Marcus Sterling',
    email: 'marcus.sterling@synchain.ai',
    role: 'Risk Analyst',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=256',
    department: 'Quantitative Risk & Geopolitical Intelligence',
    accessTier: 'Standard Executive',
  },
];
