"""Add integration fields

Revision ID: 8fd2e81ac729
Revises: c7d8e9f0a1b2
Create Date: 2026-09-14 20:03:13.499362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fd2e81ac729'
down_revision: Union[str, Sequence[str], None] = 'c7d8e9f0a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise_integrations', sa.Column('auth_type', sa.String(length=50), nullable=False))
    op.add_column('enterprise_integrations', sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('enterprise_integrations', sa.Column('status', sa.String(length=50), nullable=False))
    op.alter_column('enterprise_integrations', 'encrypted_api_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('enterprise_integrations', 'encrypted_api_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('enterprise_integrations', 'status')
    op.drop_column('enterprise_integrations', 'configuration')
    op.drop_column('enterprise_integrations', 'auth_type')
    # ### end Alembic commands ###
